"""Short-Horizon Risk Forecasting Page - 1M, 2M & 3M Ahead Predictive Early Warning."""

import json
from pathlib import Path
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from agririsk.dashboard.formatting import (
    render_disclaimer_banner,
    render_risk_badge,
    format_anomaly,
    format_zscore,
    RISK_COLORS
)
from agririsk.forecasting.features import load_forecast_dataset, FORECAST_FEATURE_COLUMNS
from agririsk.forecasting.inference import (
    load_all_forecasters,
    generate_county_multi_horizon_forecast,
    generate_early_warning_summary_table
)

st.set_page_config(
    page_title="Risk Forecasting - AgriRisk Kenya",
    page_icon="🔮",
    layout="wide"
)

# Research Disclaimer Banner
st.markdown(render_disclaimer_banner(), unsafe_allow_html=True)

# Mandatory Prototype Forecast Label
st.info(
    "📢 **IMPORTANT NOTICE:** Forecast probability generated by AgriRisk Kenya research model. "
    "Not an official IPC forecast. Official food security classifications are issued exclusively "
    "by the Kenya Food Security Steering Group (KFSSG) and the IPC Global Support Unit."
)

st.title("🔮 Short-Horizon Food-Security Risk Forecasting")
st.markdown(
    "Extending from current status assessment to **1-month, 2-month, and 3-month ahead** "
    "food-security risk forecasting across Kenya's ASAL counties to support anticipatory action."
)

# Load data and forecasters with caching
@st.cache_data
def get_forecast_dataset():
    return load_forecast_dataset()

@st.cache_resource
def get_forecasters():
    return load_all_forecasters()

forecast_df = get_forecast_dataset()
forecasters = get_forecasters()

available_counties = sorted(forecast_df["county_name"].unique().tolist())
latest_obs_period = forecast_df["observation_period"].max()

# 1. Early-Warning Multi-County Overview Table
st.subheader("📋 Early-Warning Indicator Matrix (All Pilot ASAL Counties)")
st.caption(
    "Comparing multi-horizon risk trajectories across counties. "
    "Counties are flagged with an *Elevated Model Signal* if the estimated probability exceeds the calibrated decision threshold."
)

summary_table = generate_early_warning_summary_table(latest_obs_period)
st.dataframe(
    summary_table,
    use_container_width=True,
    hide_index=True
)

st.divider()

# 2. County Multi-Horizon Drill-Down
st.subheader("📍 County Forward Forecast Drill-Down")

col_sel_c, col_sel_h = st.columns([1.5, 1.0])
with col_sel_c:
    selected_county = st.selectbox(
        "Select County:",
        options=available_counties,
        index=0,
        help="Select a county to inspect forward probability forecasts."
    )

with col_sel_h:
    selected_horizon = st.radio(
        "Focus Forecast Horizon:",
        options=["All Horizons (1M, 2M, 3M)", "1-Month Ahead (t+1)", "2-Months Ahead (t+2)", "3-Months Ahead (t+3)"],
        index=0,
        horizontal=True
    )

county_summary = generate_county_multi_horizon_forecast(selected_county, latest_obs_period)
fcasts = county_summary.get("forecasts", {})

# Top 3 Forecast Metric Cards
col_h1, col_h2, col_h3 = st.columns(3)

def render_forecast_card(container, h_key, title):
    data = fcasts.get(h_key, {})
    prob = data.get("risk_probability", 0.0)
    band = data.get("risk_band", "Low")
    target_dt = data.get("target_date", "N/A")
    alert = data.get("predicted_crisis_alert", False)
    th = data.get("decision_threshold", 0.50)

    with container:
        st.markdown(
            f"""
            <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; margin-bottom: 10px;">
                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <h4 style="margin: 0; color: #0f172a;">{title}</h4>
                    {render_risk_badge(band)}
                </div>
                <p style="margin: 4px 0 10px 0; color: #64748b; font-size: 0.85rem;">Target Month: <strong>{target_dt}</strong></p>
                <div style="font-size: 1.6rem; font-weight: bold; color: {RISK_COLORS.get(band, '#0f172a')};">
                    {prob * 100:.1f}%
                </div>
                <div style="font-size: 0.85rem; color: #475569; margin-top: 4px;">
                    Model Threshold: <code>{th:.2f}</code> | Signal: <strong>{'Elevated Alert \u26a0\ufe0f' if alert else 'Normal \u2705'}</strong>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

render_forecast_card(col_h1, "h1", "1-Month Ahead (t+1)")
render_forecast_card(col_h2, "h2", "2-Months Ahead (t+2)")
render_forecast_card(col_h3, "h3", "3-Months Ahead (t+3)")

st.divider()

# 3. Longitudinal Trajectory Chart
st.subheader(f"📈 Risk Trajectory Timeline: {selected_county}")

county_ts = forecast_df[forecast_df["county_name"] == selected_county].copy()
county_ts["observation_date"] = pd.to_datetime(county_ts["observation_date"])

# Build longitudinal timeline for each horizon
fig_timeline = go.Figure()

for h, color, dash in [(1, "#2563eb", "solid"), (2, "#7c3aed", "dash"), (3, "#d97706", "dot")]:
    h_data = county_ts[county_ts["horizon_months"] == h].sort_values("observation_date")
    h_forecaster = forecasters[h]
    probs = h_forecaster.predict_proba(h_data)

    fig_timeline.add_trace(go.Scatter(
        x=h_data["observation_period"],
        y=probs * 100,
        mode="lines+markers",
        name=f"{h}-Month Ahead Forecast (t+{h})",
        line=dict(color=color, width=2.5, dash=dash),
        marker=dict(size=4),
        hovertemplate=f"<b>{h}M Forecast</b>: %{{y:.1f}}%<extra></extra>"
    ))

# Reference lines
fig_timeline.add_hline(y=75, line_dash="dash", line_color=RISK_COLORS["High"], line_width=1, annotation_text="High Risk (75%)")
fig_timeline.add_hline(y=50, line_dash="dash", line_color=RISK_COLORS["Elevated"], line_width=1, annotation_text="Elevated Risk (50%)")
fig_timeline.add_hline(y=25, line_dash="dash", line_color=RISK_COLORS["Moderate"], line_width=1, annotation_text="Moderate Risk (25%)")

fig_timeline.update_layout(
    title=dict(text=f"<b>Multi-Horizon Risk Probability Trajectory: {selected_county}</b>", font=dict(size=14)),
    xaxis=dict(title="Observation Period", gridcolor="#f8fafc", tickangle=-30),
    yaxis=dict(title="Estimated Crisis Probability (%)", gridcolor="#f1f5f9", range=[0, 105]),
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="#ffffff",
    height=380,
    hovermode="x unified",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1.0)
)

st.plotly_chart(fig_timeline, use_container_width=True)

st.divider()

# 4. Explainability & Contributing Risk Signals
col_signals, col_calib = st.columns([1.2, 1.0])

with col_signals:
    st.subheader("🔍 Active Contributing Risk Signals")
    st.caption("Key environmental and socioeconomic indicators influencing the forward forecast:")

    h1_signals = fcasts.get("h1", {}).get("top_risk_signals", [])
    for sig in h1_signals:
        st.markdown(f"- 🔸 **{sig}**")

    st.markdown("""
    > **Non-Causal Note:** These signals represent statistical features correlated with historical 
    > food insecurity transitions. They reflect associative risk patterns and do not imply direct 
    > monocausal attribution.
    """)

    # Global feature importance for Horizon 1 forecaster
    h1_model = forecasters[1].base_model
    if hasattr(h1_model, "feature_importances_"):
        imp = h1_model.feature_importances_
        imp_df = pd.DataFrame({
            "Feature": [f.replace("_", " ").title() for f in FORECAST_FEATURE_COLUMNS],
            "Importance": imp
        }).sort_values("Importance", ascending=True).tail(8)

        fig_imp = px.bar(
            imp_df,
            x="Importance",
            y="Feature",
            orientation="h",
            title="<b>Top Global Predictors (1-Month Horizon Model)</b>",
            color="Importance",
            color_continuous_scale="Teal"
        )
        fig_imp.update_layout(
            margin=dict(l=140, r=20, t=40, b=40),
            height=280,
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="#ffffff",
            coloraxis_showscale=False
        )
        st.plotly_chart(fig_imp, use_container_width=True)

with col_calib:
    st.subheader("🎯 Model Confidence & Calibration")
    st.markdown("""
    Predictive probabilities undergo **Platt sigmoid calibration** on expanding-window validation sets 
    to ensure that an 80% forecast corresponds empirically to an ~80% observed crisis frequency.
    """)

    # Load horizon 1 JSON metrics
    h1_metrics_file = Path("reports/forecasting/horizon_1_metrics.json")
    if h1_metrics_file.exists():
        with open(h1_metrics_file, "r") as f:
            h1_data = json.load(f)

        t_met = h1_data.get("test_2024_metrics", {})
        c1, c2 = st.columns(2)
        c1.metric("1M Test Recall", f"{t_met.get('recall', 1.0) * 100:.1f}%")
        c1.metric("1M Test ROC-AUC", f"{t_met.get('roc_auc', 0.77):.3f}")
        c2.metric("1M Brier Score", f"{t_met.get('brier_score', 0.17):.4f}")
        c2.metric("Tuned Threshold", f"{h1_data.get('optimal_threshold', 0.10):.2f}")

    st.caption(
        "Threshold Tuning Rationale: Rather than defaulting to 0.50, decision thresholds are selected "
        "to satisfy a minimum 80% recall constraint on historical validation data, directly minimizing "
        "false negatives in humanitarian early warning."
    )
